version: '3'

services:
  nice-bot:
    build: ./front-end/
    container_name: nice-bot
    ports:
      - "3000:3000"
    env_file:
      - ./front-end/.env
  nice-bot-back:
    build: ./back-end/
    container_name: nice-bot-back
    ports:
      - "5000:5000"
    env_file:
      - ./back-end/.env